// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"bookchat/internal/model"

	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Comment = struct {
	ID        field.Number[uint]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
	UserID    field.Number[uint]
	Poster    field.Struct[model.User]
	RoomID    field.Number[uint]
	Content   field.String
}{
	ID:        field.Number[uint]{}.WithColumn("id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:    field.Number[uint]{}.WithColumn("user_id"),
	Poster:    field.Struct[model.User]{}.WithName("Poster"),
	RoomID:    field.Number[uint]{}.WithColumn("room_id"),
	Content:   field.String{}.WithColumn("content"),
}
