// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"bookchat/internal/model"

	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Room = struct {
	ID                field.Number[uint]
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field[gorm.DeletedAt]
	UserID            field.Number[uint]
	Moderator         field.Struct[model.User]
	Registered        field.Slice[uint]
	Title             field.String
	BookTitle         field.String
	BookAuthor        field.String
	Comments          field.Slice[model.Comment]
	ScheduledDate     field.Time
	State             field.String
	AssignedToComment field.Number[uint]
}{
	ID:                field.Number[uint]{}.WithColumn("id"),
	CreatedAt:         field.Time{}.WithColumn("created_at"),
	UpdatedAt:         field.Time{}.WithColumn("updated_at"),
	DeletedAt:         field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	UserID:            field.Number[uint]{}.WithColumn("user_id"),
	Moderator:         field.Struct[model.User]{}.WithName("Moderator"),
	Registered:        field.Slice[uint]{}.WithName("Registered"),
	Title:             field.String{}.WithColumn("title"),
	BookTitle:         field.String{}.WithColumn("book_title"),
	BookAuthor:        field.String{}.WithColumn("book_author"),
	Comments:          field.Slice[model.Comment]{}.WithName("Comments"),
	ScheduledDate:     field.Time{}.WithColumn("scheduled_date"),
	State:             field.String{}.WithColumn("state"),
	AssignedToComment: field.Number[uint]{}.WithColumn("assigned_to_comment"),
}
